### ISSUE TITLE
Firefox?

### ISSUE THREAD

**Issue by ZackeryRSmith** [ZackeryRSmith/token-stealer-but-its-one-line#4]
May add Firefox support, though this would add the `sqlite3` dependency

**Comment by mrHeavenli** [comment]
sqlite3 is usually preinstalled as far as I know.

**Comment by ZackeryRSmith** [comment]
> sqlite3 is usually preinstalled as far as I know.

Yes it is, I figured this out not too long after I created this issue. The reason I won't be adding Firefox support is to keep the Windows and Linux versions aligned. 

I will be closing this issue, I will bring it back up if firefox is ever added to the windows version.
